module.exports = [{
    id: 1,
    imageSrc: "img/p1.jpg",
    title: "Інклюзивний простір для \"особливих\" дітей і їх батьків",
    text: "Інклюзивний ХАБ - це адаптоване приміщення в центрі нашої ОТГ, де діти з інвалідністю та їх батьки зможуть реалізувати свої важливі потреби. Бо важливо - бачити серцем!",
    author: "Волиняк Дмитро",
    otgName: "Великолюбінська ОТГ",
    success: 0,
    inProcess: 1,
    categories: [1, 11],
    areaId: 6,
    communitiesId: 1045,
    durationDays: 50,
    dateStart: "2020-05-08T17:20:50.050Z",
    backerCount: 0,
    neededAmount: 30000,
    recaivedAmount: 0,

}, {
    id: 8,
    imageSrc: "img/p8.jpg",
    title: "Освічена набережна тернопільського озера.",
    text: "Найбільша окраса Тернополя це його набережна... Тож уявімо безпечні та освітлені вулиці. Також відповідного вигляду бракує замку на набережній ставу.",
    author: "Зозуляк Галина",
    otgName: "Тернопільська ОТГ",
    success: 0,
    inProcess: 0,
    categories: [1, 9],
    areaId: 2,
    communitiesId: 275,
    durationDays: 65,
    dateStart: "2020-05-08T17:20:50.050Z",
    backerCount: 0,
    neededAmount: 30000,
    recaivedAmount: 0,


}, {
    id: 2,
    imageSrc: "img/p2.jpg",
    title: "Антикафе \"Book Space\" у Бібрській ОТГ",
    text: "Book Space — це модель організації роботи і відпочинку людей різного віку, та соціальних груп, у єдиному просторі.",
    author: "Чапран Діана",
    otgName: "Бібрській ОТГ",
    success: 1,
    inProcess: 0,
    categories: [1, 5],
    areaId: 3,
    communitiesId: 545,
    durationDays: 96,
    dateStart: "2020-05-08T17:20:50.050Z",
    backerCount: 0,
    neededAmount: 30000,
    recaivedAmount: 0,

}, {
    id: 4,
    imageSrc: "img/p4.jpg",
    title: "Молодіжна галерея \"ХотАртХол\" у Мостиськах",
    text: "«ХотАртХол» - перша молодіжна галерея у Мостиській обєднаній територіальній громаді, покликана експонувати мистецькі дебюти.",
    author: "Мельничок Анастасія",
    otgName: "Мостиська ОТГ",
    success: 0,
    inProcess: 0,
    categories: [1, 6],
    areaId: 4,
    communitiesId: 5,
    durationDays: 99,
    dateStart: "2020-05-08T17:20:50.050Z",
    backerCount: 0,
    neededAmount: 30000,
    recaivedAmount: 0,

}, {
    id: 9,
    imageSrc: "img/p9.jpeg",
    title: "Приводимо до ладу дорогу Губин – Тумин!",
    text: "Ми втомилися чекати, коли держава почне щось робити, і хочемо силами двох ОТГ віреконструювати дорогу, яка нас об’єднує.",
    author: "Капустенська Марія",
    otgName: "Війницька ОТГ",
    success: 1,
    inProcess: 0,
    categories: [5, 7],
    areaId: 5,
    communitiesId: 8,
    durationDays: 99,
    dateStart: "2020-05-08T17:20:50.050Z",
    backerCount: 0,
    neededAmount: 30000,
    recaivedAmount: 0,

}, {
    id: 6,
    imageSrc: "img/p6.jpg",
    title: "\"Боже, вільна школа\" Відновлення із попелу.",
    text: "Відновлюємо після пожежі приміщення \"Боже, вільної школи\" - освітнього центру для дітей та дорослих.",
    author: "Черняк Анатолій",
    otgName: "Авангардівська ОТГ",
    success: 0,
    inProcess: 1,
    categories: [1, 6],
    areaId: 15,
    communitiesId: 10,
    durationDays: 99,
    dateStart: "2020-05-08T17:20:50.050Z",
    backerCount: 0,
    neededAmount: 30000,
    recaivedAmount: 0,

}, {
    id: 7,
    imageSrc: "img/p7.jpg",
    title: "Зробимо Зеленопідську ОТГ знову зеленою!",
    text: "Дерева - як люди, інколи хворіють, а інколи вмирають. Дерева - це наші легені Але ми губимо їх, хоча вони хочуть, щоб ми жили...",
    author: "Волиняк Дмитро",
    otgName: "Зеленопідська ОТГ",
    success: 0,
    inProcess: 1,
    categories: [2, 3],
    areaId: 7,
    communitiesId: 5,
    durationDays: 99,
    dateStart: "2020-05-08T17:20:50.050Z",
    backerCount: 0,
    neededAmount: 30000,
    recaivedAmount: 0,

}, {
    id: 5,
    imageSrc: "img/p5.jpg",
    title: "Центр творчої діяльності для дітей",
    text: "Наша мета - облаштувати кімнату \"Центр творчої діяльності\" комп'ютерним обладнанням і надати безкоштовні послуги для навчання та організації дозвілля",
    author: "Сердяк Михайло",
    otgName: "Андрушківська ОТГ",
    success: 1,
    inProcess: 0,
    categories: [3, 6],
    areaId: 8,
    communitiesId: 75,
    durationDays: 99,
    dateStart: "2020-05-08T17:20:50.050Z",
    backerCount: 0,
    neededAmount: 30000,
    recaivedAmount: 0,

}];